### ISSUE TITLE
Config Syncing

### ISSUE THREAD

**Issue by Talan67** [Floris0106/Rereskillable-Rereforked#2]
From what I read on the comments of the Curseforge page, there is still no config sync for server and client meaning players would have to manually install the server config to there client themselves or whatever method people come up with. If this is the new reskillable then it should absolutley have config sync ASAP.

**Comment by FrancoCab10** [comment]
Hello to you all.

First of all, I think config syncing is an awesome feature to add so I support this request.
BUT, I think this is not the way of asking for it mister @Talan67, you don't know how much time the developer has available, and this is his project, so you don't get to decide what HAS to be done ASAP. You should try asking nicer.

So @Floris0106, if you have the time and you think it's a fair request, please consider adding server to client config sync for the mod.

Thank you in advance,

**Comment by Floris0106** [comment]
I've thought about it a bit, and I do think that config syncing would be a good feature to implement. I'm going to look into adding it, but I don't know how long it will take.

**Comment by Floris0106** [comment]
It is done!

**Comment by Floris0106** [comment]
The updated version will be on curseforge as soon as it gets reviewed and accepted.
