### ISSUE TITLE
*Urgent* Inability to respawn when mod is in use

### ISSUE THREAD

**Issue by NafenF** [Floris0106/Rereskillable-Rereforked#21]
Specs:
Forge Version 40.1.60
RAM 6 Gigabytes
Mod version [Rereskillable Rereforked v2.1.0]
No other mods running
Ran using curse forge launcher
---------------------------------------------------------------------------------------------------------------------------------------------------
Issue:
In the latest mod version for 1.18.2, the player is unable to respawn after death. Although the player dies and is given the "Respawn" and "Title Screen" buttons, the respawn button simply doesn't work. Even after isolating the mod and resetting the config, it's still an issue.

If I had to guess, it would be from the XP loss after death function of the mod.

**Comment by Floris0106** [comment]
This is a known issue, a fix is being worked on. Closing as duplicate (of https://github.com/Floris0106/Rereskillable-Rereforked/issues/10)
