### ISSUE TITLE
When I die, I can't come back to life

### ISSUE THREAD

**Issue by moayad155** [Floris0106/Rereskillable-Rereforked#24]
I have a problem that when I die I can't come back to life (and this with mods)

**Comment by alessandriLuca** [comment]
same here , forge version 1.18.2

**Comment by Floris0106** [comment]
This is a duplicate of #10. Please first search for similar issues to see if someone has already reported a bug, before submitting an issue yourself.

**Comment by moayad155** [comment]
Is there a solution to this problem?
