### ISSUE TITLE
unable to add any new items from vanilla minecraft or mods without crash on initialisation.

### ISSUE THREAD

**Issue by SirDynamite** [Floris0106/Rereskillable-Rereforked#28]
any time i try to add a new line of text to skill lock a item, weapon/tool, or armor from vanilla minecraft or modds it will instantly crash upon starting up  saying game crashed whilst rendering overlay , exit code: -1. here is the crash log. i noticed that it mentions the : after "minecraft is not a valid option even though all the commands do this for example "minecraft:iron_sword attack:5"

https://gist.github.com/SirDynamite/6737f3926cdfd6604867ab99f78eecd1

**Comment by SirDynamite** [comment]
ok so after spending a lot of time trying different things and methods to get this to work. it finally worked for me when i copied and pasted the "code" from the read me file posted here on the site. visually it looked identical to what i have been typing up manually (and even copy pasting from the default skill locks). so i guess im no longer in any trouble but i would apreciate if someone could explain to me what might have went wrong.

**Comment by Floris0106** [comment]
Good to hear you figured it out, but in order to help you figure out what went wrong, I'll need to see the config files that did and did not work.
