### ISSUE TITLE
Level loss after death

### ISSUE THREAD

**Issue by Jollyolsport** [Floris0106/Rereskillable-Rereforked#4]
Maybe instead of having all levels drop back to zero, only a couple levels will be reduced by a small random amount after every death? Much like the first reskillable?

**Comment by Jollyolsport** [comment]
Oops Ill close and repost under suggestions.

**Comment by Floris0106** [comment]
Please do make a new issue for seperate feature suggestions, it gets quite messy if all suggestions are under one issue.

**Comment by Floris0106** [comment]
I've finally implemented this feature, should be on curseforge soon.
