### ISSUE TITLE
[Compatibility Bug] "You can't use this item yet" popup compatibility issues

### ISSUE THREAD

**Issue by Foozey** [Floris0106/Rereskillable-Rereforked#7]
Please take a look at this for reference, make sure to read iMukul's comment:
https://github.com/Momo-Studios/Cold-Sweat-Rework-Forge/issues/21

**Comment by Floris0106** [comment]
This seems to be quite a simple fix, I'll implement it as soon as I have time.

**Comment by Floris0106** [comment]
Nvm, just did it immediately. Should be on curseforge quite soon.
