### ISSUE TITLE
Update to 1.18

### ISSUE THREAD

**Issue by Floris0106** [Floris0106/Rereskillable-Rereforked#8]
Title says it all.

**Comment by Floris0106** [comment]
As I said on curseforge, I'll start porting later this week.

**Comment by Samlegamer** [comment]
Speaking of which I started porting your mod.

Here: https://github.com/Samlegamer/Rereskillable-Rereforked/tree/1.18.1

It's not all there (buggy gui), but I think I ported 75%!

**Comment by Floris0106** [comment]
I've fixed the UI issues with my version, should be on curseforge soon.
